version: 2
jobs:
  build:
    filters:
        branchs:
          only: master
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: lint
          command: npm run lint -- --mode production
      - run:
          name: unit-tests
          command: npm run test:unit
      - run:
          name: build
          command: npm run build